# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: codeepoch@gmail.com
author_name: Ezekiel Victor
contract_name: admin
deployment_language: python
preset_name: production
project_name: voting-app

